/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:31fac357-09d9-438c-97f8-ef4a8d2f9652",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_wy56eGloA",
    "aws_user_pools_web_client_id": "45ni1rce5eq2cj12e9rrdhchvk",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "geo": {
        "amazon_location_service": {
            "region": "us-east-1",
            "maps": {
                "items": {
                    "gymreacttypescriptmap-dev": {
                        "style": "VectorEsriStreets"
                    }
                },
                "default": "gymreacttypescriptmap-dev"
            }
        }
    }
};


export default awsmobile;
